const STORE_V3='jluCampV3';
const STORE_V2='jluCampV2';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const today=()=>new Date().toLocaleDateString('en-CA');
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const safe=(v)=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const defaultData=()=>({version:3,checkins:{},mocks:[],mastery:{},schedule:{},questions:[],settings:{target:375,sprint:389},achievements:[]});
function load(){try{const v3=localStorage.getItem(STORE_V3);if(v3)return Object.assign(defaultData(),JSON.parse(v3));const v2=localStorage.getItem(STORE_V2);if(v2){const d=Object.assign(defaultData(),JSON.parse(v2));d.version=3;localStorage.setItem(STORE_V3,JSON.stringify(d));return d}}catch{}return defaultData()}
let db=load();
const save=()=>localStorage.setItem(STORE_V3,JSON.stringify(db));
const toast=(t)=>{const el=$('#toast');el.textContent=t;el.style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>el.style.display='none',1800)};
const seeds=[
['民法','简述民事法律行为有效的基本条件。','行为人具有相应民事行为能力；意思表示真实；不违反法律、行政法规的强制性规定，不违背公序良俗。'],
['刑法','简述犯罪构成的一般要件。','通常从犯罪客体、犯罪客观方面、犯罪主体、犯罪主观方面展开。'],
['法理','法律规则与法律原则的主要区别是什么？','规则通常有较明确的行为模式与法律后果；原则更抽象，提供价值和理由，并具有权衡空间。'],
['宪法','我国宪法的根本法地位主要体现在哪些方面？','内容根本、法律效力最高、制定和修改程序更严格，并构成其他法律的立法基础。'],
['法制史','简述中华法系传统法律文化的一项重要特征。','可从礼法结合、家族本位、行政司法合一等角度展开，并结合制度说明。'],
['英语','What does “stare decisis” mean in legal English?','The doctrine of following judicial precedent.'],
['政治','实践与认识的辩证关系是什么？','实践是认识的来源、动力、目的和检验真理的唯一标准；认识反作用于实践。']
];
if(!db.questions?.length)db.questions=seeds.map((x,i)=>({id:i+1,cat:x[0],q:x[1],a:x[2],active:true}));
const quotes=['把可控的今天做扎实，分数自然会往上走。','不要追赶情绪，追赶完成度。','复盘不是自责，是给明天校准方向。','375 不是一句口号，是许多个普通日子的总和。','题目不会背叛你，它只会暴露还没补上的地方。','稳定比偶尔爆发更接近上岸。','把今天当作地图上唯一能点亮的一格。'];
const stages=[['基础重建','知识框架与核心概念'],['强化理解','体系串联与主观题表达'],['真题拆解','命题方式与答题结构'],['背诵成型','高频考点与输出速度'],['全真模考','时间分配与稳定得分'],['冲刺回收','错题、薄弱点、记忆回收']];
const scheduleSeed=[['08:30–12:00','397 法基','主线任务'],['14:00–17:30','497 法综','主线任务'],['19:30–21:00','英语 / 政治','支线任务'],['21:00–22:00','专业课复盘','回收任务']];
const schools=[['吉林大学',350,'985 · 目标校','JLU'],['中国人民大学',365,'985 · 四系','RUC'],['上海交通大学',360,'985','SJTU'],['华东政法大学',346,'五院','ECUPL']];
function hash(s){let h=0;for(const c of s)h=(h*31+c.charCodeAt(0))|0;return h}
function entriesSorted(){return Object.entries(db.checkins||{}).sort((a,b)=>a[0].localeCompare(b[0]))}
function dayTotal(r={}){return ['base397','comp497','english','politics'].reduce((s,k)=>s+Number(r[k]||0),0)}
function streak(){let n=0,d=new Date();if(!db.checkins[today()])d.setDate(d.getDate()-1);while(db.checkins[d.toLocaleDateString('en-CA')]){n++;d.setDate(d.getDate()-1)}return n}
function xp(){const study=entriesSorted().reduce((s,[,r])=>s+dayTotal(r),0);const checkinXp=Object.keys(db.checkins).length*20;const studyXp=Math.round(study*4);const mockXp=(db.mocks?.length||0)*50;const masteryXp=Object.values(db.mastery||{}).filter(x=>x==='会').length*5;return checkinXp+studyXp+mockXp+masteryXp}
function levelInfo(){const x=xp(),lvl=Math.floor(x/180)+1,within=x%180;const ranks=['备考新人','基础训练师','体系探索者','真题猎手','背诵锻造师','模考挑战者','吉大挑战者'];return {x,lvl,within,pct:within/180*100,rank:ranks[Math.min(ranks.length-1,Math.floor((lvl-1)/5))]}}
function renderHero(){const target=new Date('2026-12-19T00:00:00+08:00');$('#countdown').textContent=Math.max(0,Math.ceil((target-new Date())/86400000));$('#streak').textContent=streak();const li=levelInfo();$('#level').textContent='Lv.'+li.lvl;$('#rankName').textContent=li.rank;$('#xpFill').style.width=li.pct+'%';$('#xpNumber').textContent=`${li.within}/180 XP`;$('#quote').textContent=quotes[Math.abs(hash(today()))%quotes.length];$('#todayLabel').textContent=today()}
function renderToday(){const r=db.checkins[today()]||{};for(const k of ['base397','comp497','english','politics','review','blocker','tomorrow'])if($('#checkin')[k])$('#checkin')[k].value=r[k]??'';const total=dayTotal(r);$('#todayHours').textContent=total.toFixed(1)+'h';$('#questProgress').textContent=(db.schedule[today()]?Object.values(db.schedule[today()]).filter(Boolean).length:0)+'/4'}
function renderSchedule(){const key=today();db.schedule[key]??={};const now=new Date(),hm=now.getHours()*60+now.getMinutes();const ranges=[[510,720],[840,1050],[1170,1260],[1260,1320]];$('#schedule').innerHTML=scheduleSeed.map((x,i)=>`<label class="schedule-item ${db.schedule[key][i]?'done':''} ${hm>=ranges[i][0]&&hm<ranges[i][1]?'current':''}"><input type="checkbox" data-si="${i}" ${db.schedule[key][i]?'checked':''}><span class="schedule-time">${x[0]}</span><span><b>${x[1]}</b><small class="muted" style="display:block;margin-top:2px">${x[2]}</small></span><span class="quest-tag">${db.schedule[key][i]?'完成':'待挑战'}</span></label>`).join('');$$('[data-si]').forEach(c=>c.onchange=()=>{db.schedule[key][c.dataset.si]=c.checked;save();renderSchedule();renderToday();renderHero();toast(c.checked?'任务完成 + XP':'已取消完成状态')})}
function stageIndex(){const m=new Date().getMonth()+1;const day=new Date().getDate();if(m<=8)return 1;if(m===9)return 2;if(m===10)return 3;if(m===11&&day<=15)return 4;if(m===11||m===12&&day<=8)return 5;return 6}
function renderStages(){const cur=stageIndex();$('#stages').innerHTML=stages.map((s,i)=>`<div class="stage ${i+1<cur?'done':''} ${i+1===cur?'now':''}"><span class="stage-dot">${i+1}</span><span><b>${s[0]}</b><small>${s[1]}</small></span><span class="mini-score">${i+1===cur?'当前区域':i+1<cur?'已通过':'未解锁'}</span></div>`).join('');$('#stageNow').textContent=`第 ${cur} 阶段`}
let qi=0;
function activeQuestions(){return db.questions.filter(x=>x.active!==false)}
function renderDailyQuestion(){const pool=activeQuestions();if(!pool.length)return;qi=((Math.abs(hash(today()))+qi)%pool.length+pool.length)%pool.length;const q=pool[qi];$('#qcat').textContent=q.cat;$('#dailyQ').textContent=q.q;$('#dailyA').textContent=q.a;$('#dailyA').hidden=true;$('#answerBtn').textContent='查看解析';$('#dailyMastery').textContent=db.mastery[q.id]||'未评估'}
function rows(n){if(n>=9999)return entriesSorted();const cutoff=Date.now()-(n-1)*86400000;return entriesSorted().filter(([d])=>new Date(d).getTime()>=cutoff)}
function renderData(){const rs=rows(Number($('#range')?.value||7));const hrs=rs.reduce((s,[,r])=>s+dayTotal(r),0),avg=rs.length?hrs/rs.length:0;const mastered=Object.values(db.mastery).filter(x=>x==='会').length;$('#metrics').innerHTML=[[hrs.toFixed(1),'学习小时','⚡'],[rs.length,'打卡天数','◆'],[avg.toFixed(1),'日均小时','◈'],[mastered,'已掌握题','✦']].map(x=>`<div class="metric"><span>${x[2]} ${x[1]}</span><strong>${x[0]}</strong></div>`).join('');const sums={base397:0,comp497:0,english:0,politics:0};rs.forEach(([,r])=>Object.keys(sums).forEach(k=>sums[k]+=Number(r[k]||0)));const max=Math.max(1,...Object.values(sums));const labels=[['397 法基','base397'],['497 法综','comp497'],['英语一','english'],['政治','politics']];$('#subjectBars').innerHTML=labels.map(([n,k])=>`<div class="bar-row"><b>${n}</b><div class="bar"><i style="width:${sums[k]/max*100}%"></i></div><span>${sums[k].toFixed(1)}h</span></div>`).join('');const weak=Object.values(db.mastery).filter(x=>x!=='会').length;const weakest=labels.sort((a,b)=>sums[a[1]]-sums[b[1]])[0]?.[0]||'暂无';$('#weekly').innerHTML=`<p><b>本周期累计 ${hrs.toFixed(1)} 小时。</b> 当前最需要补强的是 <b>${weakest}</b>。</p><p class="muted">题库中有 ${weak} 道处于“模糊 / 不会”状态。下一轮优先把低时长科目、弱题和最近一次模考失分点串成一条补弱路线。</p>`;const hist=[...entriesSorted()].reverse();$('#history').innerHTML=hist.length?`<table><tr><th>日期</th><th>397</th><th>497</th><th>英语</th><th>政治</th><th>总时长</th><th>复盘</th></tr>${hist.map(([d,r])=>`<tr><td>${d}</td><td>${r.base397||0}</td><td>${r.comp497||0}</td><td>${r.english||0}</td><td>${r.politics||0}</td><td><b>${dayTotal(r).toFixed(1)}</b></td><td>${safe(r.review||'')}</td></tr>`).join('')}</table>`:'<div class="empty">还没有历史记录，今天就是第一格地图。</div>'}
function renderMock(){const list=[...(db.mocks||[])].reverse();$('#mockList').innerHTML=list.length?list.map(r=>`<div class="item boss-card"><div class="item-top"><b>${safe(r.date)}</b><span class="pill">${r.total} 分</span></div><div class="boss-meter"><i style="width:${clamp(r.total/389*100,0,100)}%"></i></div><div class="mini-score">政治 ${r.politics} · 英语 ${r.english} · 397 ${r.base397} · 497 ${r.comp497}</div><p class="muted">距 375：${r.total>=375?'+':''}${r.total-375} · ${safe(r.notes||'暂无复盘')}</p></div>`).join(''):'<div class="empty">还没有 Boss 战记录。第一次全真模考会在这里留下战报。</div>';const latest=list[0];$('#bossScore').textContent=latest?latest.total:'--';$('#bossGap').textContent=latest?`${latest.total>=375?'+':''}${latest.total-375}`:'--'}
function renderQuestions(){const term=($('#qSearch')?.value||'').toLowerCase(),cat=$('#qFilter')?.value||'all';const list=db.questions.filter(q=>(cat==='all'||q.cat===cat)&&(!term||(q.q+q.a+q.cat).toLowerCase().includes(term)));$('#qList').innerHTML=list.length?list.map(q=>`<div class="item"><div class="item-top"><b>${safe(q.cat)}</b><span class="pill">${safe(db.mastery[q.id]||'未评')}</span></div><p>${safe(q.q)}</p><div class="muted">${safe(q.a)}</div></div>`).join(''):'<div class="empty">没有匹配题目。</div>'}
function renderSchools(){$('#schoolList').innerHTML=schools.map(s=>`<div class="item school-card ${s[0]==='吉林大学'?'target-school':''}"><div class="school-mark">${s[3]}</div><div><b>${s[0]}</b><div class="muted">${s[2]} · 2026 复试口径快照</div></div><span class="pill">${s[1]} 分</span></div>`).join('')}
function openPhotoDB(){return new Promise((ok,no)=>{const r=indexedDB.open('jluCampPhotos',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('photos'))r.result.createObjectStore('photos',{keyPath:'id'})};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function renderPhotos(){try{const d=await openPhotoDB(),tx=d.transaction('photos'),r=tx.objectStore('photos').getAll();r.onsuccess=()=>{const arr=r.result.sort((a,b)=>b.date.localeCompare(a.date));$('#gallery').innerHTML=arr.length?arr.map(p=>`<div class="photo"><img src="${p.data}" alt="学习记录"><div class="caption"><b>${safe(p.date)}</b><br>${safe(p.caption||'')}</div></div>`).join(''):'<div class="empty">照片墙还是空的。把阶段纪念、书桌或模考记录留在这里。</div>';d.close()}}catch{}}
function renderAll(){renderHero();renderToday();renderSchedule();renderStages();renderData();renderMock();renderQuestions();renderSchools();renderPhotos()}
$('#nav').addEventListener('click',e=>{const b=e.target.closest('button[data-view]');if(!b)return;$$('#nav button').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(v=>v.classList.toggle('active',v.id===b.dataset.view));renderAll();scrollTo({top:0,behavior:'smooth'})});
$('#checkin').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),r={};for(const [k,v] of f)r[k]=['review','blocker','tomorrow'].includes(k)?v:Number(v||0);db.checkins[today()]=r;save();renderAll();toast(`今日记录已保存 · ${dayTotal(r).toFixed(1)}h`) });
$('#answerBtn').onclick=()=>{const a=$('#dailyA');a.hidden=!a.hidden;$('#answerBtn').textContent=a.hidden?'查看解析':'收起解析'};
$('#switchBtn').onclick=()=>{qi++;renderDailyQuestion()};
$$('.mastery').forEach(b=>b.onclick=()=>{const pool=activeQuestions();if(!pool.length)return;const q=pool[qi%pool.length];db.mastery[q.id]=b.dataset.m;save();renderDailyQuestion();renderHero();toast('掌握度：'+b.dataset.m)});
$('#range').onchange=renderData;
$('#historyBtn').onclick=()=>{const d=prompt('补录日期 YYYY-MM-DD');if(!d)return;db.checkins[d]??={base397:0,comp497:0,english:0,politics:0,review:'',blocker:'',tomorrow:''};save();renderData();toast('已创建补录日期')};
$('#mockForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),r=Object.fromEntries(f);['politics','english','base397','comp497'].forEach(k=>r[k]=Number(r[k]||0));r.total=r.politics+r.english+r.base397+r.comp497;db.mocks.push(r);save();renderMock();renderHero();toast(`Boss 战记录 +50 XP · ${r.total}分`);e.target.reset();e.target.date.value=today()});
$('#qSearch').oninput=renderQuestions;$('#qFilter').onchange=renderQuestions;
$('#addQ').onclick=()=>{const cat=prompt('分类：民法 / 刑法 / 法理 / 宪法 / 法制史 / 英语 / 政治');if(!cat)return;const q=prompt('题目');if(!q)return;const a=prompt('答案')||'';db.questions.push({id:Date.now(),cat,q,a,active:true});save();renderQuestions();toast('题目已加入训练池')};
$('#photoForm').addEventListener('submit',async e=>{e.preventDefault();const fs=[...$('#photoFiles').files].slice(0,12);if(!fs.length)return toast('请选择照片');const d=await openPhotoDB(),tx=d.transaction('photos','readwrite'),st=tx.objectStore('photos');for(const f of fs){if(f.size>10*1024*1024)continue;const data=await new Promise(ok=>{const r=new FileReader;r.onload=()=>ok(r.result);r.readAsDataURL(f)});st.put({id:Date.now()+Math.random(),date:$('#photoDate').value||today(),caption:$('#photoCaption').value,data})}tx.oncomplete=()=>{d.close();$('#photoFiles').value='';renderPhotos();toast('照片已写入训练日志')}});
$('#exportBtn').onclick=()=>{const payload={...db,exportedAt:new Date().toISOString()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='jlu-study-backup-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
$('#importBtn').onclick=()=>{const f=$('#importFile').files[0];if(!f)return toast('请选择 JSON');const r=new FileReader;r.onload=()=>{try{const incoming=JSON.parse(r.result);db=Object.assign(defaultData(),incoming,{version:3});save();renderAll();toast('备份已恢复')}catch{toast('JSON 无法读取')}};r.readAsText(f)};
$('#photoDate').value=today();$('#mockForm [name=date]').value=today();renderDailyQuestion();renderAll();